// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAY0_WNGDWWw8WHihUMDj2a8zx1yUAOJI',
    appId: '1:867582911189:web:ed9e8fb378ad032321785c',
    messagingSenderId: '867582911189',
    projectId: 'blaundry-d26d1',
    authDomain: 'blaundry-d26d1.firebaseapp.com',
    storageBucket: 'blaundry-d26d1.firebasestorage.app',
    measurementId: 'G-8XB9QH784Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfep6uK_KzqC_m0BMWIFwxTPg4TnVgj3k',
    appId: '1:867582911189:android:f53b4725e1eb14e421785c',
    messagingSenderId: '867582911189',
    projectId: 'blaundry-d26d1',
    storageBucket: 'blaundry-d26d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgR3Mv5eCYekeTdIb2UXVb66VmIufuLc',
    appId: '1:867582911189:ios:29e2a51f6ad3af4221785c',
    messagingSenderId: '867582911189',
    projectId: 'blaundry-d26d1',
    storageBucket: 'blaundry-d26d1.firebasestorage.app',
    iosBundleId: 'com.example.blaundryRegistlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgR3Mv5eCYekeTdIb2UXVb66VmIufuLc',
    appId: '1:867582911189:ios:29e2a51f6ad3af4221785c',
    messagingSenderId: '867582911189',
    projectId: 'blaundry-d26d1',
    storageBucket: 'blaundry-d26d1.firebasestorage.app',
    iosBundleId: 'com.example.blaundryRegistlogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAY0_WNGDWWw8WHihUMDj2a8zx1yUAOJI',
    appId: '1:867582911189:web:bbeaf0a03db3c60021785c',
    messagingSenderId: '867582911189',
    projectId: 'blaundry-d26d1',
    authDomain: 'blaundry-d26d1.firebaseapp.com',
    storageBucket: 'blaundry-d26d1.firebasestorage.app',
    measurementId: 'G-C05C005QFM',
  );
}
